controller_list:
  - name: fake_arm_controller
    joints:
      - junta1
      - junta2
      - junta3
      - junta4
      - junta5
  - name: fake_grip_controller
    joints:
      - ligarra
      - palm_riser
      - palm_left_finger
      - left_finger_tip
      - palm_right_finger
      - right_finger_tip
initial:  # Define initial robot poses.
  - group: arm
    pose: home