arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - base
     - ligacao
     - braco
     - antepunho
     - punho
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      base: {trajectory: 0.1, goal: 0.1}
      ligacao: {trajectory: 0.1, goal: 0.1}
      braco: {trajectory: 0.1, goal: 0.1}
      antepunho: {trajectory: 0.1, goal: 0.1}
      punho: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - base
     - ligacao
     - braco
     - antepunho
     - punho