robot:

  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint0_position_controller:
   type: position_controllers/JointTrajectoryController
   joint: junta1
   pid: {p: 10000.0, i: 0.01, d: 10.0}
  joint1_position_controller:
   type: position_controllers/JointTrajectoryController
   joint: junta2
   pid: {p: 10000.0, i: 0.01, d: 10.0}
  joint2_position_controller:
   type: position_controllers/JointTrajectoryController
   joint: junta3
   pid: {p: 10000.0, i: 0.01, d: 10.0}
  joint3_position_controller:
   type: position_controllers/JointTrajectoryController
   joint: junta4
   pid: {p: 10000.0, i: 0.01, d: 10.0}
  joint4_position_controller:
   type: position_controllers/JointTrajectoryController
   joint: junta5
   pid: {p: 10000.0, i: 0.01, d: 10.0}
  joint5_position_controller:
   type: position_controllers/JointTrajectoryController
   joint: ligarra
   pid: {p: 10000.0, i: 0.01, d: 10.0}
  joint6_position_controller:
   type: position_controllers/JointTrajectoryController
   joint: palm_riser
   pid: {p: 10000.0, i: 0.01, d: 10.0}
  joint7_position_controller:
   type: position_controllers/JointTrajectoryController
   joint: palm_left_finger
   pid: {p: 10000.0, i: 0.01, d: 10.0}
  joint8_position_controller:
   type: position_controllers/JointTrajectoryController
   joint: left_finger_tip
   pid: {p: 10000.0, i: 0.01, d: 10.0}
  joint9_position_controller:
   type: position_controllers/JointTrajectoryController
   joint: palm_right_finger
   pid: {p: 10000.0, i: 0.01, d: 10.0}
  joint10_position_controller:
   type: position_controllers/JointTrajectoryController
   joint: right_finger_tip
   pid: {p: 10000.0, i: 0.01, d: 10.0}
