# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: robot_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - junta1
    - junta2
    - junta3
    - junta4
    - junta5
    - ligarra
    - palm_riser
    - palm_left_finger
    - left_finger_tip
    - palm_right_finger
    - right_finger_tip
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
gripper_controller:
  type: effort_controllers/JointPositionController
  joints:
    - ligarra
    - palm_riser
    - palm_left_finger
    - left_finger_tip
    - palm_right_finger
    - right_finger_tip
  gains:
    ligarra:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    palm_riser:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    palm_left_finger:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_finger_tip:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    palm_right_finger:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_finger_tip:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
robot_arm_controller:
  type: effort_controllers/JointPositionController
  joints:
    - junta1
    - junta2
    - junta3
    - junta4
    - junta5
  gains:
    junta1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    junta2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    junta3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    junta4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    junta5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1